#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

sudo apt-get install -y python-setuptools python-dev build-essential
sudo easy_install pip

cd /opt/distributor-agent/
pip install -r requirements.txt
python setup.py install
cp etc/initd/distributor-agent /etc/init.d/

mkdir /etc/octavia
# we assume certs, etc will come in through the config drive
mkdir /etc/octavia/certs
mkdir /var/lib/octavia

